### ISSUE TITLE
Other options OK, but jq -c seems to confuse the parser

### ISSUE THREAD

**Issue by lleeoo** [davidnussio/vscode-jq-playground#52]
On MacOS 10.14.6, VS 1.46.1, JQ Playground 3.2.2

# -r works fine:
```
jq -r .
{"name":"JSON", "good":true}
```
produces
```
{
  "name": "JSON",
  "good": true
}
```

# -c causes an error
```
jq -c .
{"name":"JSON", "good":true}
```
It seems to interpret the entire line as an option (notice the `.`).
```
/usr/local/bin/jq: Unknown option -c .
```

# possible fix
Also looking at [this file](https://github.com/davidnussio/vscode-jq-playground/blob/master/src/command-line.ts#L20) we see that `-c` is not on the list. And indeed, using `--compact-output`, which is on the list, works: 
```
jq --compact-output .
{"name":"JSON", "good":true}
```
produces
```
{"name":"JSON","good":true}
```

BTW ctrl+enter and shift+enter don't work either.

**Comment by davidnussio** [comment]
Thanks for the report the issue I released the patch.

Are you reporting problems with keyboard shortcuts on mac?

**Comment by davidnussio** [comment]
Ok, maybe you are using jq as languageId. Try change to jqpg (jq PlayGround). I decided to enabled this shortcuts only in this context to avoid conflicts with plain jq files.

**Comment by lleeoo** [comment]
Thanks for the fix on -c.

re the shortcuts: I can confirm that if I change to "jqpg" then Apple+Enter
works for the "Output", but Shift+Enter still does not work.
